import { useMemo, useCallback, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import type { Filters, MapDisplay, DistrictPop, Facility } from '@/types/dashboard';
import { costCategory, enrichDistricts, matchesDistrictFilters, matchesFacilityFilters } from '@/lib/dashboardData';

export const DEFAULT_FILTERS: Filters = {
  divisions: [], districts: [], facilityTypes: [], ownership: [], origin: [],
  services: [], category: [], appointmentRequired: [], cost: [], searchQuery: '',
  povertyRange: [0, 100], literacyRange: [0, 100], urbanRange: [0, 100],
  populationRange: [0, 50000000], facilitiesRange: [0, 200],
};
const DEFAULT_MAP: MapDisplay = {
  showChoropleth: true, showMarkers: true, showHeatmap: false, showBubbles: false,
  showLabels: false, choroplethMetric: 'facilities', bubbleMetric: 'facilities',
};
const LIST_KEYS = {
  divisions: 'div', districts: 'd', facilityTypes: 'ft', ownership: 'o', origin: 'or',
  services: 's', category: 'cat', appointmentRequired: 'ap', cost: 'c',
} as const;
const RANGE_KEYS = {
  povertyRange: 'pr', literacyRange: 'lr', urbanRange: 'ur', populationRange: 'pop', facilitiesRange: 'fr',
} as const;

function readList(params: URLSearchParams, key: string): string[] {
  const values = params.getAll(key);
  if (values.length !== 1) return values.filter(Boolean);
  try {
    const parsed: unknown = JSON.parse(values[0]);
    if (Array.isArray(parsed) && parsed.every(v => typeof v === 'string')) return parsed;
  } catch { /* Support links generated by previous versions. */ }
  return values[0].split(',').filter(Boolean);
}
function readFilters(params: URLSearchParams): Filters {
  const filters = { ...DEFAULT_FILTERS, searchQuery: params.get('q') || '' };
  for (const key of Object.keys(LIST_KEYS) as (keyof typeof LIST_KEYS)[]) filters[key] = readList(params, LIST_KEYS[key]);
  for (const key of Object.keys(RANGE_KEYS) as (keyof typeof RANGE_KEYS)[]) {
    const numbers = (params.get(RANGE_KEYS[key]) || '').split(',').map(Number);
    if (numbers.length === 2 && numbers.every(Number.isFinite) && numbers[0] >= 0 && numbers[0] <= numbers[1]) filters[key] = [numbers[0], numbers[1]];
  }
  return filters;
}
function readMap(params: URLSearchParams): MapDisplay {
  try {
    const value = JSON.parse(params.get('map') || '{}') as Partial<MapDisplay>;
    const result = { ...DEFAULT_MAP };
    for (const key of ['showChoropleth', 'showMarkers', 'showHeatmap', 'showBubbles', 'showLabels'] as const) {
      if (typeof value[key] === 'boolean') result[key] = value[key];
    }
    if (['facilities', 'population', 'facilitiesPer100k', 'populationPerFacility', 'povertyIndex', 'literacyRate', 'urbanPercent'].includes(value.choroplethMetric || '')) result.choroplethMetric = value.choroplethMetric!;
    if (['facilities', 'population', 'facilitiesPer100k'].includes(value.bubbleMetric || '')) result.bubbleMetric = value.bubbleMetric!;
    return result;
  } catch { return DEFAULT_MAP; }
}

export function useFilters(allDistricts: DistrictPop[], allFacilities: Facility[]) {
  const [params, setParams] = useSearchParams();
  const latestParams = useRef(params);
  latestParams.current = params;
  const commit = useCallback((change: (next: URLSearchParams) => void) => {
    const next = new URLSearchParams(latestParams.current);
    change(next);
    latestParams.current = next;
    setParams(next, { replace: true });
  }, [setParams]);
  const filters = useMemo(() => readFilters(params), [params]);
  const mapDisplay = useMemo(() => readMap(params), [params]);
  const selectedDistrict = params.get('sel') || null;

  const updateFilter = useCallback(<K extends keyof Filters>(key: K, value: Filters[K]) => {
    commit(next => {
      const param = key === 'searchQuery' ? 'q' : LIST_KEYS[key as keyof typeof LIST_KEYS] || RANGE_KEYS[key as keyof typeof RANGE_KEYS];
      const serialized = key === 'searchQuery' ? String(value) : key in LIST_KEYS ? (value as string[]).length ? JSON.stringify(value) : '' : (value as number[]).join(',');
      if (serialized) next.set(param, serialized); else next.delete(param);
      if (key === 'divisions' || key === 'districts') next.delete('sel');
    });
  }, [commit]);
  const updateMapDisplay = useCallback(<K extends keyof MapDisplay>(key: K, value: MapDisplay[K]) => {
    commit(next => {
      next.set('map', JSON.stringify({ ...readMap(next), [key]: value }));
    });
  }, [commit]);
  const setSelectedDistrict = useCallback((code: string | null) => {
    commit(next => {
      if (code) next.set('sel', code); else next.delete('sel');
    });
  }, [commit]);
  const resetFilters = useCallback(() => {
    commit(next => {
      [...Object.values(LIST_KEYS), ...Object.values(RANGE_KEYS), 'q', 'sel'].forEach(key => next.delete(key));
    });
  }, [commit]);

  const nationallyFilteredFacilities = useMemo(() => allFacilities.filter(f => matchesFacilityFilters(f, filters)), [allFacilities, filters]);
  const nationalDistricts = useMemo(() => enrichDistricts(allDistricts, nationallyFilteredFacilities), [allDistricts, nationallyFilteredFacilities]);
  const geographicDistricts = useMemo(() => allDistricts.filter(d => matchesDistrictFilters(d, filters, selectedDistrict)), [allDistricts, filters, selectedDistrict]);
  const activeFacilities = useMemo(() => {
    const codes = new Set(geographicDistricts.map(d => d.DIS_CODE));
    return nationallyFilteredFacilities.filter(f => codes.has(f.DIS_CODE));
  }, [geographicDistricts, nationallyFilteredFacilities]);
  const activeDistricts = useMemo(() => enrichDistricts(geographicDistricts, activeFacilities), [geographicDistricts, activeFacilities]);
  const filterOptions = useMemo(() => {
    const unique = (values: (string | undefined)[]) => [...new Set(values.filter((v): v is string => Boolean(v)))].sort();
    const divisions = [...new Map(allDistricts.map(d => [d.DIV_CODE, d.DIV_NAME])).entries()].map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name));
    return {
      divisions,
      districts: allDistricts.map(d => ({ code: d.DIS_CODE, name: d.DIS_NAME, divisionCode: d.DIV_CODE })).sort((a, b) => a.name.localeCompare(b.name)),
      facilityTypes: unique(allFacilities.map(f => f.facility_type)), ownership: unique(allFacilities.map(f => f.ownership)),
      origin: unique(allFacilities.map(f => f.origin)), services: unique(allFacilities.map(f => f.services_provided)),
      category: unique(allFacilities.map(f => f.category_adult_child_both)), appointmentRequired: unique(allFacilities.map(f => f.appointment_required)),
      cost: unique(allFacilities.map(f => costCategory(f.cost))),
    };
  }, [allDistricts, allFacilities]);
  return { filters, updateFilter, resetFilters, mapDisplay, updateMapDisplay, selectedDistrict, setSelectedDistrict, activeDistricts, activeFacilities, nationalDistricts, filterOptions };
}
